version: '3'

services:
  alticci:
    build: .
    container_name: alticci-service
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      USE_REDIS: "True"
      CACHE_DEFAULT_TIMEOUT: "60"
      CACHE_REDIS_HOST: "0.0.0.0"
      CACHE_REDIS_PORT: "6379"

  redis:
    image: redis:7-alpine
    container_name: alticci-redis
    ports:
      - "6379:6379"
